### ISSUE TITLE
Define the data format for a calibration/profile.

### ISSUE THREAD

**Issue by alastairtree** [ImperialCollegeLondon/mag-lab-data-platform#5]
Data file with list of offsets, also misalignment of sensors and gains. We can then later apply this to a L1 data file to generate a layer towards L2.

**Comment by mhairifin** [comment]
Define an initial data format for a calibration profile. A data file in this format could be applied to an L1 data file to generate a layer towards L2 data, or a complete L2 data file.

- Can capture time series of offsets
- Can capture other calibration parameters 
- Can potentially express different layers of calibration
- Can potentially express metadata about the calibration (methodology, events that triggered an offset change)
- Is potentially "human readable" as well as machine ingestible, to make it easy for a person to easily view the offset layers if necessary.

**Comment by mhairifin** [comment]
Preliminary file format:

[calibrations.json](https://github.com/user-attachments/files/16330659/calibrations.json)

Calibrations could also be put into separate files (so they can be generated independently), that can be applied individually to an L1 (or pre-L2) data file.

**Comment by alastairtree** [comment]
I think this looks good for a first go, nice work! Thanks! I suspect we will need to be able to apply it in multiple files but no harm in being able to have more than one calibration in a file **and** be able to have multiple calibrations in multiple files.

Have you got any python to generate and parse a file like that? I have been using pydantic to define model classes see [here](https://github.com/ImperialCollegeLondon/imap-pipline-core/blob/main/src/appConfig.py) and [here](https://github.com/ImperialCollegeLondon/imap-pipline-core/blob/main/src/main.py#L31) and then binding them to yaml (which is interchangeable with json) so if not that might be a way?
